[build-system]
requires = [
	'setuptools',
	'wheel',
	'setuptools-scm'
]
build-backend = 'setuptools.build_meta'

[project]
name = 'Squishy'
description = 'SCSI Multitool and Amaranth HDL Library'
license = 'BSD-3-Clause'
classifiers = [
	'Development Status :: 4 - Beta',

	'Environment :: Console',

	'Intended Audience :: Developers',
	'Intended Audience :: Information Technology',
	'Intended Audience :: System Administrators',

	'License :: OSI Approved :: BSD License',

	'Operating System :: MacOS :: MacOS X',
	'Operating System :: Microsoft :: Windows',
	'Operating System :: POSIX :: Linux',

	'Programming Language :: Python :: 3.8',
	'Programming Language :: Python :: 3.9',
	'Programming Language :: Python :: 3.10',

	'Topic :: Software Development',
	'Topic :: System :: Hardware'
]

dependencies = [
	'Jinja2',
	'construct>=2.10.67',
	'arrow',
	'libusb1>=1.8.1',
	'rich~=12.2.0',

	'amaranth @ git+https://github.com/amaranth-lang/amaranth.git@main',
	'amaranth-boards @ git+https://github.com/amaranth-lang/amaranth-boards.git@main',
	'amaranth-stdio @ git+https://github.com/amaranth-lang/amaranth-stdio.git@main',

	'usb_protocol @ git+https://github.com/shrine-maiden-heavy-industries/python-usb-protocol@main',
	'luna @ git+https://github.com/shrine-maiden-heavy-industries/luna.git@main'
]

dynamic = [
	'version',
	'readme'
]


[project.optional-dependencies]
toolchain = [
	'yowasp-yosys',
	'yowasp-nextpnr-ice40-8k',
	'yowasp-nextpnr-ecp5-45k'
]
firmware = [
	'meson',
	'ninja'
]
gui = [
	'PySide2~=5.15.2'
]

[tool.setuptools.dynamic]
version = {attr = 'squishy.__version__'}
readme = {file = ['README.md']}
