name: "Squishy Docs"
on:
  push:
    branches:
      - 'main'
jobs:
  document:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Initialize Environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Setup
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          sudo pip3 install --upgrade pip setuptools wheel
          pip3 install --user -r ./docs/requirements.txt
          pip3 install --user .
      - name: Build Docs
        shell: bash
        run: |
          sphinx-build -b html ./docs ./_build/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _build
          clean: true
