name: "Squishy Tests"
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize Environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
          echo "TORII_TEST_INHIBIT_VCD=1" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - name: Setup OSS CAD Suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: Run Tests
        shell: bash
        run: |
          nox -s test -- --coverage

      - name: Codecov Upload
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          files: ./build/tests/coverage.xml
