name: "Squishy Tests"
on:
  push: {}
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize Environment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
          echo "SQUISHY_TEST_INHIBIT_VCD=1" >> $GITHUB_ENV
          echo "AMARANTH_USE_YOSYS=builtin" >> $GITHUB_ENV
          echo "YOSYS=yowasp-yosys" >> $GITHUB_ENV
          echo "SBY=yowasp-sby" >> $GITHUB_ENV
          echo "SMTBMC=yowasp-yosys-smtbmc" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Setup
        shell: bash
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys FA8E1301F4D3932C
          sudo add-apt-repository 'deb http://ppa.launchpad.net/sri-csl/formal-methods/ubuntu bionic main'
          sudo apt-get update
          sudo apt-get install yices2
          sudo pip3 install --upgrade pip setuptools wheel testresources
          pip3 install --user yowasp-yosys coverage codecov
          pip3 install --user -e .[toolchain,gui]
      - name: Preserve Wasm cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.cache/wasmtime
            ~/.cache/yowasp
          key: ${{ runner.os }}-wasm
      - name: Run Tests
        shell: bash
        run: |
          python -m coverage run -m unittest discover -t . -s .
          codecov
